name: Build XPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install zip
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Build XPI
        run: |
          VERSION=${GITHUB_REF_NAME}
          FILE="build/tab-todotxt-${VERSION}.xpi"
          echo "FILE=$FILE" >> $GITHUB_ENV
          mkdir -p build
          zip -r "$FILE" . -x "*.git*" "*.github*" "build/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-xpi
          path: ${{ env.FILE }}
