name: Build XPI

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install zip
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Build XPI
        run: |
          VERSION=${GITHUB_REF_NAME}
          FILE="build/tab-todotxt-${VERSION}.xpi"

          echo "Building version: $VERSION"
          echo "FILE=$FILE" >> $GITHUB_ENV

          mkdir -p build

          zip -r "$FILE" . \
            -x "*.git*" \
            -x "*.github*" \
            -x "build/*" \

      - name: Create GitHub Release and upload XPI
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: ${{ env.FILE }}
